#! /bin/bash
set -e

if [[ $# -ne 1 ]]; then
    echo "[USAGE] run_sql <sql-query>"
    exit 1
else
    SQL_QUERY=$1
fi

TEMP_PWD_FILE=tmp.cnf
touch $TEMP_PWD_FILE
chmod 600 $TEMP_PWD_FILE
printf "[client]\npassword=%s\n" $MYSQL_ROOT_PASSWORD > $TEMP_PWD_FILE

mysql --defaults-file=$TEMP_PWD_FILE -uroot --execute="$SQL_QUERY"

rm $TEMP_PWD_FILE
