#! /bin/bash
set -e

if [[ $# -ne 2 ]]; then
    echo "[USAGE] run_sql <db-root-password> <sql-query>"
    exit 1
else
    PASSWORD=$1
    SQL_QUERY=$2
fi

TEMP_PWD_FILE=tmp.cnf
touch $TEMP_PWD_FILE
chmod 600 $TEMP_PWD_FILE
printf "[client]\npassword=%s\n" $PASSWORD > $TEMP_PWD_FILE

mysql --defaults-file=$TEMP_PWD_FILE -uroot --execute="$SQL_QUERY"

rm $TEMP_PWD_FILE
