DROP DATABASE IF EXISTS rtt_migration_info;
CREATE DATABASE IF NOT EXISTS rtt_migration_info;
USE rtt_migration_info;

CREATE TABLE IF NOT EXISTS applied_migrations (
    id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    number BIGINT UNSIGNED UNIQUE NOT NULL,
    filename VARCHAR(1024) UNIQUE NOT NULL
) ENGINE = INNODB;
